include_defs('//bucklets/maven_jar.bucklet')

VER = '2.12.2'
REPO = MAVEN_CENTRAL

maven_jar(
  name = 'plugin-api',
  id = 'com.google.gerrit:gerrit-plugin-api:' + VER,
  sha1 = 'FixMe',
  license = 'Apache2.0',
  attach_source = False,
  repository = REPO,
)

maven_jar(
  name = 'gwtui-api',
  id = 'com.google.gerrit:gerrit-plugin-gwtui:' + VER,
  sha1 = 'FixMe',
  license = 'Apache2.0',
  attach_source = False,
  repository = REPO,
)
